add select dropdown for tech stack, prevent forms from empty submission, limit description lengths
san-diego-tech-hub/sdth-site pull request #175
Opened 2019-08-29 21:46 UTC by radiylonmina

This commit adds a "Tech Stack" select dropdown to the Job Seekers form.  This allows users to select various languages, frameworks, and libraries and have it be displayed as tags on the Job Candidate cards.  The description for each card has been limited to 350 characters, but has a "Read more" button that will expand the rest of the text.  The description box for each form has been limited to 700 characters max to keep Resource card sizes uniform.  This commit also adds a solution to prevent empty forms from submitting to the database.

2019-09-03 00:11 UTC, appleJax requested changes
Nice! Just a few things to clean up, see comments...

2019-09-03 00:11 UTC, appleJax commented on src/components/forms/job-seekers.js
> +    $name: name!,
Is this supposed to be
```js
$name: String!,
```
?

2019-09-03 00:11 UTC, appleJax commented on src/components/forms/speakers.js
> +    $name: name!,
Is this supposed to be
```js
$name: String!,
```
?

2019-09-03 00:11 UTC, appleJax commented on src/components/forms/job-seekers.js
> +        <label htmlFor="techStack">
Eslint is complaining here, I think it's because it doesn't recognize `react-select` as an input. You can just put `{/* eslint-disable-next-line */}` on line 162. Also, make sure you have eslint enabled in your editor.

2019-09-03 00:11 UTC, appleJax commented on src/components/forms/job-seekers.js
> +          <Select
You can pass `name="techStack"` to the `Select` component to associate it with the label.

2019-09-03 00:11 UTC, appleJax commented on src/components/forms/venues.js
> +      $name: name!,
Is this supposed to be
```js
$name: String!,
```
?

2019-09-03 00:11 UTC, appleJax commented on src/components/network/resources/JobCandidateCard.js
> +                  <Button key={display}
`Button` is not defined. Did you mean to make a styled component instead of `.read-more-button`?

2019-09-03 00:11 UTC, appleJax commented on src/components/network/resources/JobCandidateCard.js
> +  const [display, setDisplay] = useState(4)
`useState` is not defined.

2019-09-03 00:11 UTC, appleJax commented on src/components/network/resources/LocationCard.js
> +  const [display, setDisplay] = useState(4)
`useState` is not defined.

2019-09-03 00:11 UTC, appleJax commented on src/components/network/resources/LocationCard.js
> +                  <Button key={display}
`Button` is not defined. Did you mean to make a styled component instead of `.read-more-button`?

2019-09-03 17:12 UTC, radiylonmina commented on src/components/forms/job-seekers.js
> +    $name: name!,
Variable type needs to be name! to match Hasura data type.  Tested using String! instead and form breaks.

2019-09-03 17:12 UTC, radiylonmina commented on src/components/forms/speakers.js
> +    $name: name!,
Variable type needs to be name! to match Hasura data type.  Tested using String! instead and form breaks.

2019-09-03 17:14 UTC, radiylonmina commented on src/components/forms/job-seekers.js
> +        <label htmlFor="techStack">
Added the line, my mistake.

2019-09-03 17:15 UTC, radiylonmina commented on src/components/forms/job-seekers.js
> +          <Select
Added.

2019-09-03 17:19 UTC, radiylonmina commented on src/components/forms/venues.js
> +      $name: name!,
Variable type needs to be name! to match Hasura data type. Tested using String! instead and form breaks.

2019-09-03 17:22 UTC, radiylonmina commented on src/components/network/resources/JobCandidateCard.js
> +  const [display, setDisplay] = useState(4)
Added missing useState import.

2019-09-03 17:22 UTC, radiylonmina commented on src/components/network/resources/LocationCard.js
> +  const [display, setDisplay] = useState(4)
Added missing useState import.

2019-09-03 17:49 UTC, radiylonmina commented on src/components/network/resources/JobCandidateCard.js
> +                  <Button key={display}
```.read-more-button``` is an internal class within the ```read-more-react``` package used to the style the description's "Read more" button, so it's separate from this issue.

Working on adding Button styled component and fixing tag toggle issue.

2019-09-03 17:49 UTC, radiylonmina commented on src/components/network/resources/LocationCard.js
> +                  <Button key={display}
.read-more-button is an internal class within the read-more-react package used to the style the description's "Read more" button, so it's separate from this issue.

Working on adding Button styled component and fixing tag toggle issue.

2019-09-03 18:02 UTC, radiylonmina commented on src/components/network/resources/LocationCard.js
> +                  <Button key={display}
Seems like some code was removed during our merge to each other's forks.  Added styled component for Button, fixed tag toggle issue.

2019-09-03 18:02 UTC, radiylonmina commented on src/components/network/resources/JobCandidateCard.js
> +                  <Button key={display}
Seems like some code was removed during our merge to each other's forks.  Added styled component for Button, fixed tag toggle issue.

2019-09-04 03:23 UTC, appleJax approved these changes
Thank you, great job! 🙌

2019-09-04 03:23 UTC, merged